denoland/dnt

- cli.ts
- lib/_args.ts
I'm not sure this is a right way to do this in this code base, but this PR adds `-h, --help` options to the cli.
> feat: add -h, --help options

- deno.json
- lib/compiler.test.ts
- lib/compiler.ts
- mod.ts
- tests/integration.test.ts
> feat: support creating source maps

- lib/package_json.test.ts
- lib/package_json.ts
- mod.ts
- tests/integration.test.ts
> feat: add `importHelpers` compiler option and align with ts compiler default of `false`

- README.md
> docs: recommend having output directory ignored by source control

- lib/package_json.test.ts
- mod.ts
- rs-lib/src/visitors/deno_globals.rs
- rs-lib/tests/integration_test.rs
- tests/integration.test.ts
- tests/shim_project/mod.test.ts
- tests/shim_project/mod.ts
> fix: shim `setTimeout` and `setInterval`

- README.md
> docs: add instructions for creating an automation token

- rs-lib/src/visitors/deno_globals.rs
- rs-lib/tests/integration_test.rs
> fix: do not inject Deno namespace into globalThis in property access expression when next identifier is not Deno

- lib/pkg/dnt_wasm.js
- rs-lib/Cargo.toml
- rs-lib/src/visitors/analyze/get_top_level_decls.rs
- rs-lib/src/visitors/analyze/helpers.rs
- rs-lib/src/visitors/analyze/mod.rs
- rs-lib/src/visitors/deno_globals.rs
- rs-lib/src/visitors/mod.rs
- rs-lib/tests/integration_test.rs
> fix: shim incorrectly injected for global type name when local type of same name exists

- mod.ts
> fix: emit `"use strict";`

- rs-lib/src/polyfills/scripts/object-has-own.ts
- tests/integration.test.ts
- tests/polyfill_project/mod.ts
Accidentally pushed to the main branch and forgot to format (protected branches must not apply to me since I'm an admin).
Edit: I've now enforced this for admins.
> chore: format

- lib/pkg/dnt_wasm.js
- rs-lib/src/lib.rs
- rs-lib/src/mappings.rs
- rs-lib/src/utils.rs
- rs-lib/src/visitors/imports_exports.rs
- rs-lib/tests/integration_test.rs
This improve the json module implementation.
> feat: support using export declaration with a json module

- README.md
- rs-lib/src/visitors/deno_globals.rs
- rs-lib/tests/integration_test.rs
- tests/integration.test.ts
- tests/redirects_project/mod.test.ts
> feat: convert `window` global to `globalThis`

- README.md
- rs-lib/src/lib.rs
- rs-lib/src/loader/specifier_mappers.rs
- rs-lib/tests/integration/test_builder.rs
- rs-lib/tests/integration_test.rs
- transform.ts
> feat: support mapping specifiers to npm package sub paths

- lib/compiler.ts
- mod.ts
This transpiles the test_runner.js code to the specified target.
> fix: transform test runner code to specifier compiler option target

- README.md
- lib/pkg/dnt_wasm.js
- lib/shims.test.ts
- lib/shims.ts
- rs-lib/src/lib.rs
- rs-lib/tests/integration/test_builder.rs
- rs-lib/tests/integration_test.rs
- tests/integration.test.ts
- tests/shim_project/mod.test.ts
- tests/shim_project/mod.ts
- transform.ts
> feat: ability to specify "types" package for shim. Also, add `DOMException` shim

- lib/pkg/dnt_wasm.d.ts
- lib/pkg/dnt_wasm.js
- mod.ts
- rs-lib/Cargo.toml
- rs-lib/src/graph.rs
- rs-lib/src/lib.rs
- rs-lib/src/mappings.rs
- rs-lib/src/visitors/globals.rs
- rs-lib/tests/integration/test_builder.rs
- rs-lib/tests/integration_test.rs
- tests/import_map_project/add/mod.ts
- tests/import_map_project/add/other.ts
- tests/import_map_project/import_map.json
- tests/import_map_project/mod.ts
- tests/import_map_project/mod_testfile.ts
- tests/integration.test.ts
- transform.ts
- wasm/src/lib.rs
> feat: support import maps

- README.md
- lib/compiler_transforms.ts
- lib/npm_ignore.test.ts
- lib/npm_ignore.ts
- lib/package_json.test.ts
- lib/package_json.ts
- lib/test_runner/get_test_runner_code.test.ts
- lib/test_runner/get_test_runner_code.ts
- mod.ts
- tests/integration.test.ts
> feat: ability to specify cjs or umd output

- README.md
Accidentally merged this experiment to the readme.
> docs: fix custom shims section in readme.md

- rs-lib/src/mappings.rs
I thought about how I didn't test this scenario and it was indeed broken when I wrote some tests for it.
> fix: win path length truncation should not panic on `.d.ts` files

- rs-lib/src/lib.rs
- rs-lib/src/utils.rs
- rs-lib/src/visitors/globals.rs
- rs-lib/tests/integration_test.rs
> feat: inject import declarations after leading trivia

- README.md
- lib/shims.test.ts
- lib/shims.ts
- tests/integration.test.ts
- tests/web_socket_project/mod.test.ts
- tests/web_socket_project/mod.ts
- tests/web_socket_server.ts
> feat: add shim for WebSocket

- lib/package_json.ts
- lib/shims.ts
- tests/integration.test.ts
- tests/undici_project/mod.ts
> feat: upgrade undici to 5.3 & automatically include @types/node dev dependency for undici

- rs-lib/src/polyfills/array_find_last.rs
- rs-lib/src/polyfills/mod.rs
- rs-lib/src/polyfills/scripts/esnext.array-findLast.ts
- rs-lib/tests/integration_test.rs
- tests/integration.test.ts
- tests/polyfill_array_find_last_project/mod.ts
- tests/polyfill_array_find_last_project/mod_test.ts
> feat: add `Array.prototype.findLast` and `findLastIndex` polyfills

- rs-lib/src/polyfills/scripts/esnext.error-cause.ts
- tests/integration.test.ts
> fix: correct `Error#cause` typings

- mod.ts
- tests/integration.test.ts
- tests/node_types_project/main.ts
> fix: ensure that `@types/...` packages are resolved in more scenarios

- lib/mod.deps.ts
> fix: better pnpm support

- lib/shims.ts
- tests/integration.test.ts
Undici has a MITM vulnerability https://github.com/nodejs/undici/security/advisories/GHSA-pgw7-wx7w-2w33 so upgrading.
> fix: upgrade undici to 5.5.1

- README.md
- lib/package_json.test.ts
- lib/package_json.ts
- lib/pkg/dnt_wasm.generated.js
- lib/shims.ts
- lib/test_runner/test_runner.ts
- rs-lib/src/lib.rs
- rs-lib/src/loader/specifier_mappers.rs
- rs-lib/tests/integration/test_builder.rs
- rs-lib/tests/integration_test.rs
- tests/integration.test.ts
- transform.ts
> feat: support peer dependencies in mappings

- mod.ts
> feat: add skipLibCheck option and enable by default

- mod.ts
- tests/integration.test.ts
- tests/node_types_project/main.ts
See https://github.com/denoland/dnt/issues/185#issuecomment-1176754205
> chore: add tests for custom Node TextEncoder/Decoder shim

- lib/package_json.test.ts
- lib/package_json.ts
- tests/integration.test.ts
Aligns with what's mentioned in https://github.com/microsoft/TypeScript/pull/44501#issuecomment-1207320104
> fix: correct exports in package.json

- lib/test_runner/test_runner.ts
- tests/test_project/mod.test.ts
> fix: ensure test context's name is set

- README.md
Aligns the documentation for multiple entry points with the changes introduced in `0.31.0` (https://github.com/denoland/dnt/pull/221).
> Update docs for multiple entry points

- lib/utils.ts
- mod.ts
- tests/integration.test.ts
> feat: support providing file urls in build options

- README.md
> docs: add documentation for using an import map

- mod.ts
> feat: add more type checking compiler options

- deno.jsonc
- lib/pkg/dnt_wasm.generated.js
> fix: cache wasm file locally after first run

- .gitignore
- lib/compiler.ts
- lib/mod.deps.ts
- lib/pkg/snippets/dnt-wasm-a15ef721fa5290c5/helpers.js
- lib/test.deps.ts
- lib/transform.deps.ts
- mod.ts
- rs-lib/tests/integration_test.rs
- tests/integration.test.ts
- tests/polyfill_project/mod.test.ts
- tests/test_project/mod.test.ts
- tests/using_decl_project/mod.test.ts
- tests/using_decl_project/mod.ts
- tests/web_socket_project/mod.test.ts
- tests/web_socket_server.ts
- wasm/helpers.js
> feat: upgrade to TypeScript 5.2

- lib/package_json.test.ts
- lib/package_json.ts
- lib/utils.test.ts
- lib/utils.ts
- tests/integration.test.ts
This is so that https://arethetypeswrong.github.io/ can provide information about how the package was generated by dnt.
Closes https://github.com/denoland/dnt/issues/335
> feat: add _generatedBy to package.json for arethetypeswrong

- mod.ts
Closes https://github.com/denoland/dnt/issues/353
> fix: warn when someone specifies 'files' in a package.json

- mod.ts
> feat: make stripInternal configurable and default to `false`

- deno.lock
- tests/jsr_project/mod.test.ts
- tests/jsr_project/mod.ts
> chore: pin `@std` dep

- rs-lib/src/polyfills/mod.rs
> feat: don't generate polyfills when script target is Latest

- rs-lib/src/lib.rs
I don't have time atm for a test, but I manually tested this.
Closes https://github.com/denoland/dnt/issues/467
> fix: do not resolve package.json deps to node_modules folder
