lib/npm_ignore.test.ts
lib/npm_ignore.ts
mod.ts

I've added a jsdoc remark recommending not to do this when creating a hybrid package (the default) since it will duplicate the sources in the final package.
Closes #19

feat: support inlining sources in source maps

---

lib/pkg/dnt_wasm.js
mod.ts
tests/integration.test.ts
tests/mappings_project/mod.test.ts
tests/mappings_project/mod.ts
wasm/src/lib.rs

This was accidentally not working because the mappings weren't being properly passed to the rust code.

fix: ensure mappings get passed to rust

---

rs-lib/src/visitors/deno_globals.rs
rs-lib/tests/integration_test.rs

Closes #22.
Also fixes a few more edge cases.

fix: do not insert shim for globalThis directly in unary and binary expressions

---

mod.ts
tests/integration.test.ts
tests/test_project/mod.test.ts

fix(types): fix types with global fallback (such as `Headers`)

---

README.md
rs-lib/src/lib.rs
rs-lib/src/visitors/analyze/get_ignore_line_indexes.rs
rs-lib/tests/integration_test.rs

This will give a warning for now if using the old one.
Closes #62

feat: rename `// deno-shim-ignore` to `// dnt-shim-ignore`

---

README.md
lib/pkg/dnt_wasm.js
rs-lib/src/lib.rs
rs-lib/src/scripts/createMergeProxy.test.ts
rs-lib/src/scripts/createMergeProxy.ts
rs-lib/src/visitors/globals.rs
rs-lib/tests/integration/test_builder.rs
rs-lib/tests/integration_test.rs
tests/integration.test.ts
transform.ts

This PR adds a `globalThis` proxy shim, which will be more correct and faster than the previous `({ ..globalThis, ..dntShim })` business that was going on before.
Additionaly, since shimming is a bit more complicated now there needed a way to be able to say "this global is type only". So now that can be done by setting the `typeOnly` property on the `GlobalName` to true:
```ts
globalNames: [{
name: "MyType",
typeOnly: true,
}],
```

feat: `globalThis` proxy shim

---

README.md
lib/npm_ignore.test.ts
lib/npm_ignore.ts
lib/utils.ts
mod.ts
tests/integration.test.ts

This PR introduces a new build option: `packageManager` which allows to use Yarn or pnpm.

feat: allow to override package manager

---

README.md
lib/package_json.ts
lib/shims.test.ts
lib/shims.ts
lib/test_runner/get_test_runner_code.test.ts
lib/test_runner/get_test_runner_code.ts
mod.ts
tests/integration.test.ts
tests/redirects_project/node_file.ts
tests/redirects_project/output.node.ts

For running `Deno.test` code on very old node versions where the `Deno` shim might not work at the moment.

feat: add `Deno.test`-only shim

---

lib/compiler.test.ts
lib/compiler.ts
lib/pkg/dnt_wasm.js
lib/types.ts
mod.ts
rs-lib/src/lib.rs
rs-lib/src/polyfills/error_cause.rs
rs-lib/src/polyfills/mod.rs
rs-lib/src/polyfills/object_has_own.rs
rs-lib/src/polyfills/scripts/error-cause.ts
rs-lib/src/polyfills/scripts/string-replaceAll.ts
rs-lib/src/polyfills/string_replace_all.rs
rs-lib/src/visitors/polyfill.rs
rs-lib/tests/integration/test_builder.rs
rs-lib/tests/integration_test.rs
transform.ts
wasm/src/lib.rs

feat: polyfill based on target and `String.prototype.replaceAll` polyfill

---

lib/test_runner/get_test_runner_code.test.ts
lib/test_runner/get_test_runner_code.ts

The generated test script did not actually fail when `require(umdPath)` throws.
Wrapping it in a try catch and explicitly calling `process.exit(1)` seems to do the trick.
This resolves #86

fix: actually fail when require(umdPath) throws

---

README.md
lib/shims.ts
rs-lib/src/lib.rs
rs-lib/src/visitors/globals.rs
rs-lib/tests/integration_test.rs
tests/integration.test.ts

This is more correct. The `dntGlobalThisType` wasn't correct because it didn't really merge with the `globalThis` type (ex. `WeakRef` fell apart because it used generics). I don't see any way to make that work in TypeScript actually, so this PR changes it to inline `globalThis.X` shim types to `dntShim.X`.

fix: remove `dntGlobalThisType` and try to inline `globalThis.X` shim types directly instead

---

mod.ts

Previously it logs "Running npm install..." though using another package manager. This PR fixes this.

fix: respect package manager in logs when installing

---

rs-lib/src/loader/specifier_mappers.rs
rs-lib/tests/integration_test.rs

This PR will allow imports like this:
```js
import pkg1 from 'https://cdn.skypack.dev/preact@^10.5.0/hooks?dts';
import pkg2 from 'https://esm.sh/react-dom@17.0.2/server';
```

feat: support sub path in CDN imports

---

rs-lib/Cargo.toml
rs-lib/src/lib.rs
rs-lib/src/loader/specifier_mappers.rs
rs-lib/src/mappings.rs
rs-lib/src/visitors/deno_comment_directives.rs

"once_cell" is preferred in Rust community at the moment. [More details.](https://docs.rs/once_cell/latest/once_cell/#faq)

refactor: switch from "lazy_static" to "once_cell"

---

lib/test_runner/test_runner.test.ts
lib/test_runner/test_runner.ts
tests/test_project/mod.test.ts

Accidentally had my dnt side property name as `ignored` instead of `ignore`
Closes #123

fix: test runner was not respecting `ignore`

---

lib/compiler.test.ts
lib/compiler.ts
mod.ts

Currently `dnt` cannot detect TLA like
```ts
if (condition) {
await test();
}
for await (const item of items){ }
```

fix: complete logic in `getTopLevelAwait` function

---

lib/compiler_transforms.test.ts
lib/compiler_transforms.ts

closes #106 
This PR replaces `import.meta.main` with `(require.main === module)`.

feat: replace import.meta.main in CJS

---

rs-lib/src/declaration_file_resolution.rs
rs-lib/src/specifiers.rs
rs-lib/tests/integration_test.rs

`deno-types` with skypack dts (using ?dts option) does not throw error because its' `media_type` is Javascript, not Dts.
When using esm.sh instead, the Dts file is correctly labeled using their extension.
So, I remove mapped declaration specifiers from `declaration_file_mappings` to resolve errors related to finding mapped declaration specifiers in `mapping`.
If you have a better idea or plan, feel free to comment because I am a newcomer to this repo and rustlang. thanks 😊
resolves #139

Fix not to add mapped declaration file in `specifier.types`

---

rs-lib/src/lib.rs
rs-lib/tests/integration_test.rs

Web Stream API can be used in the latest nodejs with `node:stream/web` import. (https://nodejs.org/api/webstreams.html#web-streams-api)
But the module name with node scheme in custom shims option occurs error because it can be parsed to Url (which is `ModuleSpecifier`. 
So I changed `ModuleShim::maybe_specifier` not to allow URL with `node` scheme.

fix: Support custom shim w/ node scheme

---

mod.ts

This allows people to do some action after building and before running tests. For example, they could manually fix up some issue in the code.

feat: add `postBuild` action

---

lib/package_json.test.ts
lib/package_json.ts
tests/integration.test.ts
tests/json_module_project/mod.test.ts

The state of tooling understanding exports is still really bad, so don't include it.

fix: do not use `exports` for cjs only package

---

mod.ts

isolatedModules, experimentalDecorators, emitDecoratorMetadata

feat: add `emitDecoratorMetadata` compiler option

---

lib/compiler.ts

fix: support NO_COLOR for ts diagnostics

---

README.md
lib/package_json.test.ts
lib/package_json.ts
tests/integration.test.ts

Fixes https://github.com/denoland/dnt/issues/228.
>Webpack expects that the default property is always the last one inside of an exports object. (The Nodejs documentation for the exports field mentions that the order is important: look for "key order is signficant" in [https://nodejs.org/api/packages.html](https://nodejs.org/api/packages.html#:~:text=key%20order%20is%20significant). Here's an example of another project running into this issue and fixing it by reordering the properties: https://github.com/transitive-bullshit/chatgpt-api/pull/25.)
This PR is made up of three commits:
1. Adds a test for the fix.
2. Fixes the bug.
3. Cosmetic changes in the readme and multiple tests to always show the default key as last.

fix: exports types resolution in package.json

---

.github/workflows/ci.yml
mod.ts
tests/integration.test.ts

This will emit the declaration files beside the .js files in both the esm and cjs folders.

feat: add `declaration: "inline"` option for emitting declaration files beside js files

---

lib/types.ts

Hi,
With this update deno dnt config, will enforce some standard format for the package.json content.
the more strict the typing is the less bug you have.

feat: complete PackageJsonObject model

---

README.md

This PR updates the readme with up-to-date instructions for setting up a GitHub Action to trigger publishing of package to npm when tags are created in a repo.
The current instructions still work as of today, but they produce deprecation warnings by GitHub Actions.
The proposed updates in this PR fixes all current warnings.
See
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

docs: update GitHub Action instructions

---

README.md
mod.ts
tests/integration.test.ts

feat: ability to filter typescript diagnostics

---

Cargo.lock

Fixes: `webpki: CPU denial of service in certificate path building`

chore: cargo update to fix webpki vuln warning

---

mod.ts

This PR adds a `skipInstallDeps` option (`false` by default), which allows to skip the `npm install` step (or whatever package manager you're using).
I would like to include a `prepare`-script in an npm package. This `prepare`-script runs automatically during `npm install`, which I would like to avoid.

feat: add skipNpmInstall option

---

lib/pkg/dnt_wasm.generated.js
lib/pkg/snippets/dnt-wasm-a15ef721fa5290c5/helpers.js
rs-lib/src/graph.rs
rs-lib/src/lib.rs
rs-lib/src/loader/default_loader.rs
rs-lib/src/loader/mod.rs
rs-lib/tests/integration/in_memory_loader.rs
wasm/helpers.js
wasm/src/lib.rs

Fix here is to upgrade to the latest deno_cache. The cache setting stuff is just bonus that hooks this up for the replacement registry.
Closes https://github.com/denoland/dnt/issues/340

fix: fetch https dependencies with retries

---

lib/package_json.test.ts
lib/package_json.ts

The name and version were way down

fix: ensure package.json entries are in a reasonable order

---

rs-lib/src/polyfills/scripts/esnext.array-fromAsync.ts

The "exclude" in deno.json is nice, but not so nice in this scenario as it prevents formatting.
I didn't bother running a wasm build because this is not a big deal.

fix: remove needless semi-colon in fromAsync.ts

---

mod.ts
tests/integration.test.ts

adds support for being able to configure the [`declarationMap`](https://www.typescriptlang.org/tsconfig#declarationMap) option. this is very useful when using go to definition in editors as it will take you directly to the `.ts` source code (if published) rather than the output `.d.ts` or `.js` files.

feat: make declarationMap configurable and enable by default

---

deno.jsonc

It was excluding files found in the module graph.

chore: fix publish exclude

---

lib/utils.test.ts
lib/utils.ts

When wanting to map jsr packages to npm it would be nice to not crash.
example
```ts
await build({
// ...
mappings: {
'jsr:@mr/object-identity': {
name: 'object-identity',
version: '^1'
}
} 
});
```
```shell
$ deno task build
error: Uncaught (in promise) "The following specifiers were indicated to be mapped to a package, but were not found:\n  * file:///Users/stuff/jsr:@mr/object-identity"
```
I am not 100% sure this will fix the issue, but sounds promising 🙏🏻

fix: allow jsr packages to be mapped

---

deno.jsonc
deno.lock

Per discussion on #407 - opening this despite not having fully tested end-to-end locally that this does in fact allow TS5.4+ features. However, repo tests are passing.

feat: upgrade @ts-morph/bootstrap to 0.23 (#407)

---

README.md
lib/package_json.test.ts
lib/package_json.ts
tests/integration.test.ts

Without it, npm complains about it:
```
npm WARN publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm WARN publish errors corrected:
npm WARN publish Removed invalid "scripts"
```
via https://github.com/npm/cli/issues/6918 it looks like this is not going to be fixed, thus the change, which removes the warnings

fix: missing `scripts` section

---

mod.ts

This PR introduces the `experimentalDecorators` option to the TypeScript compiler in the dnt project. This allows disabling legacy decorators, which are currently hardcoded as true
Currently, dnt enforces the use of legacy decorators, which conflicts with modern decorators. This causes errors both at compile time and runtime. For example:
This issue occurs because the emitted JavaScript relies on legacy decorators, which are incompatible with the expected behavior and types of modern decorators.
- Adds support for explicitly configuring the `experimentalDecorators` compiler option.
- The default behavior remains unchanged (legacy decorators enabled) to avoid breaking existing projects, but developers can now disable it as needed.

feat: add `experimentalDecorators` compiler option

---

mod.ts

feat(BREAKING): es decorators by default
